// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-4r7Sx5FGufqlnSrfZTUq4FVcSAeKq7c',
    appId: '1:580135829375:web:b2a7600e32c68e9987e44a',
    messagingSenderId: '580135829375',
    projectId: 'meditrack-5ecbc',
    authDomain: 'meditrack-5ecbc.firebaseapp.com',
    storageBucket: 'meditrack-5ecbc.firebasestorage.app',
    measurementId: 'G-VT1SRDGCVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtcykvq2eZDIqOqvLYa2454J07-JmV3tg',
    appId: '1:580135829375:android:aad0f3bf173adf5587e44a',
    messagingSenderId: '580135829375',
    projectId: 'meditrack-5ecbc',
    storageBucket: 'meditrack-5ecbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDENuB0kJuIOQWtTdRY5GcoBng1eeiJlkI',
    appId: '1:580135829375:ios:6c184e207c62999387e44a',
    messagingSenderId: '580135829375',
    projectId: 'meditrack-5ecbc',
    storageBucket: 'meditrack-5ecbc.firebasestorage.app',
    androidClientId: '580135829375-41sj0t10k5aain1d6j3bf5ob720clte7.apps.googleusercontent.com',
    iosClientId: '580135829375-g2tpil6m41cog7i5kuvi9hdubqn90oo2.apps.googleusercontent.com',
    iosBundleId: 'com.example.maditrack',
  );

}